# Generated by Django 3.2.22 on 2023-11-05 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogphoto',
            name='image',
            field=models.ImageField(default='default', upload_to='images/', verbose_name='image'),
        ),
    ]
