# Generated by Django 3.2.22 on 2023-11-07 12:39

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dogblog', '0003_likephoto_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogphoto',
            name='image',
            field=cloudinary.models.CloudinaryField(default='default', max_length=255, verbose_name='image'),
        ),
    ]
