# Generated by Django 3.2.22 on 2023-11-07 12:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dogblog', '0004_alter_dogphoto_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likephoto',
            name='likes',
        ),
        migrations.AddField(
            model_name='dogphoto',
            name='likes',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
